# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-DNS-Zone-Parser
version:      0.02
version_from: Parser.pm
installdirs:  site
requires:
    File::Basename:                0
    File::Temp:                    0
    IO::File:                      0
    Net::DNS:                      0.64
    Net::DNS::SEC:                 0.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
